cadastrapp:
  image: camptocamp/georchestra_cadastrapp:1.5
  imagePullPolicy: Always
  # If defined, this will be used to pull the docker image
  #imagePullSecrets:
  #  - name: myPullSecret
  env_variables:
    JAVA_OPTIONS: -Duser.language=fr -Duser.country=FR
    XMX: 512m
  datadir:
    git:
      url: git@github.com:georchestra/datadir.git
      ref: "22.0"
      # the chart expects to have a k8s secret with an entry named "ssh-privatekey"
      # containing the private key allowed to clone the git repository above.
      #ssh_secret: mySshSecret
