apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadastrapp.fullname" . }}-cadastrapp-svc
  labels:
    {{- include "cadastrapp.labels" . | nindent 4 }}
    app.georchestra.org: cadastrapp    
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: 8080
  selector:
    {{- include "cadastrapp.selectorLabels" . | nindent 4 }}
